export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTAILS: 'INVALID_CREDENTIALS',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  INVALID_EMAIL_ADDRESS: 'INVALID_EMAIL_ADDRESS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_SESSION: 'INVALID_SESSION',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Account / Resource
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',

  // Request
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_PERMISSIONS: 'MISSING_PERMISSIONS',

  // HTTP
  UNAUTHORIZED: 'UNAUTHORIZED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Integration
  NOT_CONNECTED: 'NOT_CONNECTED',

  // Tokens
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_EXCHANGE_FAILED: 'TOKEN_EXCHANGE_FAILED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',

  // Email
  SEND_EMAIL_ERROR: 'SEND_EMAIL_ERROR',

  // External API
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',

  // Server
  SERVER_MISCONFIGURATION: 'SERVER_MISCONFIGURATION',
};
